networks:
  mysql:
    driver: bridge

services:
    mysql:
      image: 'mysql:8.0.20'
      deploy:
        resources:
          limits:
            cpus: '0.2'
            memory: "512M"
      ports:
        - '3306:3306'
      environment:
        - MYSQL_ROOT_PASSWORD=123456
      volumes:
        - ./mysql/data:/var/lib/mysql
        - ./mysql/conf:/etc/mysql/conf.d
        - ./mysql/my.cnf:/etc/mysql/my.cnf
      networks:
        - mysql
