version: "3"
services:
  mysql:
    image: 'mysql:latest'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - SERVICE_NAME=mysql
      - SERVICE_TAGS=db,mysql
      - SERVICE_REGION=DC1
